//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfficeChat
{
    using System;
    using System.Collections.Generic;
    
    public partial class Messages2
    {
        public string message { get; set; }
        public System.DateTime date { get; set; }
        public string postID { get; set; }
        public bool sent_recieved { get; set; }
        public string targetUser { get; set; }
        public string userName { get; set; }
    }
}
